### ISSUE TITLE
recovering wallet from old hard drive w/o pass phrase (can provide small reward if recovered)

### ISSUE THREAD

**Issue by machim1** [zkSNACKs/WasabiDoc#1013]
My laptop crashed and i loaded my old wasabi files from the hard drive, having issues getting the old wallet to load.

**Comment by BTCparadigm** [comment]
Move the file to C:\Users\YourUsername\AppData\Roaming\WalletWasabi\Client\Wallets

When you load the wallet, wait till it synchronizes. You should see "Ready" in the bottom left corner of the wallet when it's done.

**Comment by machim1** [comment]
So i did move some files into the wallet folder. Only thing is im not sure which file is the wallet. The ones i tried might just be short cuts bc wasabi kept crashing when i tried to open them.

**Comment by machim1** [comment]
im seeing a 
wasabi wallet folder - shortcut- 2kb
wasabee - application- 205kb
wasabeed - application -205kb

**Comment by machim1** [comment]
the top one crashes wasabi and the other two do not load at all

**Comment by lontivero** [comment]
@machim1 

It would be good to know what operating system you were using in your old machine and what operating system you are using int your new machine in order to provide you the correct step to step help that you need. This is because Wasabi stores things in different locations for different operating systems.

Regardless of that, the best way to recover your wallet is by simply installing Wasabi in your new computer and recover your wallet using your recovery words.

In case you don't have your recovery words then you can use the data folder in your old machine and copy it into your new machine but we need more info if you want more detailed help.

**Comment by yahiheb** [comment]
Here is where you can find the Wasabi data folder: 
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#where-can-i-find-the-wasabi-data-folder

Inside the `Client` folder you will find the `Wallets` folder, and there you can find your wallet file, something like: `WalletName.json`.

Copy that wallet file to the Wasabi data folder on your new laptop, and edit it by setting the `Height` to `0` like:
`"Height": "0"`

Then start Wasabi and wait for your wallet to synchronize.

**Comment by machim1** [comment]
Windows 10 on both. Thanks guys ill keep trying and let you know if i figure it out. Still seems like the only data folder i can find is in Wasabi Wallet >TorDaemons > Data Folder.....no wallet inside.

**Comment by yahiheb** [comment]
> Windows 10 on both. Thanks guys ill keep trying and let you know if i figure it out. Still seems like the only data folder i can find is in Wasabi Wallet >TorDaemons > Data Folder.....no wallet inside.

You are looking at the wrong place.

> Here is where you can find the Wasabi data folder:
> https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#where-can-i-find-the-wasabi-data-folder
> 
> Inside the `Client` folder you will find the `Wallets` folder, and there you can find your wallet file, something like: `WalletName.json`.
> 
> Copy that wallet file to the Wasabi data folder on your new laptop, and edit it by setting the `Height` to `0` like:
> `"Height": "0"`
> 
> Then start Wasabi and wait for your wallet to synchronize.

**Comment by MarnixCroes** [comment]
stale, closing
