### ISSUE TITLE
Search bar not working sometimes (with new added FAQs)

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1239]
Looking up `WHAT DOES THE PRIVACY PROGRESS MEAN?` in the search bar does not return anything.

**Comment by MarnixCroes** [comment]
indeed something wrong, also notice that it still called `Wallet Manager`, which is incorrect as it has been renamed to `General`
![image](https://user-images.githubusercontent.com/93143998/193082603-c65e21d8-0314-43c5-95aa-a20dc834ad1f.png)

**Comment by yahiheb** [comment]
cc @CAnorbo

**Comment by jesseaam** [comment]
## Notes 
I looked into this issue and want to document some things I noticed - it's basically a documentation of my learning journey. This might help someone with more knowledge/experience know what the next steps should be. 

---

<br>

1. It appears to be the case that the search functionality is not working for just the chapter `...FAQ/FAQ-UseWasabi.html`. The other chapters in this FAQ page are working within the search bar. So I tried to discover why that particular chapter wasn't being indexed in the search. 
2. I did some investigating into how we use search in our documentation. From what I could tell, we use a module called `node_modules/docsearch.js`. The README within this directory describes: 
```
DocSearch will crawl your documentation website, push its content to an Algolia
index, and allow you to add a dropdown search menu for your users to find
relevant content in no time.
Check out our https://community.algolia.com/docsearch/ for a complete explanation and documentation.
```
3. So then I searched `https://community.algolia.com/docsearch/` and got a 404 file not found.
4. I went back to the README and seen:
```
DocSearch is made of 3 repositories:

https://github.com/algolia/docsearch contains the `docsearch.js` code source and the
  documentation website.
https://github.com/algolia/docsearch-configs contains the JSON files representing all the
  configs for all the documentations DocSearch is powering
https://github.com/algolia/docsearch-scraper contains the crawler we use to extract data
  from your documentation. The code is open-source and you can run it from
  a Docker image
```
but both the docsearch-configs and docsearch-scraper repos show they are deprecated.
5. Then I searched within the file `package-lock.json` in our WasabiDoc for the package docsearch. I saw:
```
"node_modules/docsearch.js": {
      "version": "2.6.3",
      "resolved": "https://registry.npmjs.org/docsearch.js/-/docsearch.js-2.6.3.tgz",
      "integrity": "sha512-GN+MBozuyz664ycpZY0ecdQE0ND/LSgJKhTLA0/v3arIS3S1Rpf2OJz6A35ReMsm91V5apcmzr5/kM84cvUg+A==",
      "deprecated": "This package has been deprecated and is no longer maintained. Please use @docsearch/js.",
```
6. I figure that it is because this package is deprecated that the search functionality is not working properly in our docs. So we might want to explore using [@docsearch/js ](https://www.npmjs.com/package/@docsearch/js).
7. I also pulled down [PR #1247](https://github.com/zkSNACKs/WasabiDoc/pull/1247) and see that docsearch is no longer included. Instead it looks like the headers-based search plugin [@vuepress/plugin-search](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/plugin-search) is used instead. So maybe this is the best solution.

<br><br>

Anyways, hope this helps.

**Comment by jesseaam** [comment]
I've been working on this - the docs uses [Algolia](https://www.algolia.com) for searching. This is a platform that gives more functionality than the search box [@vuepress/plugin-search](https://vuepress.vuejs.org/plugin/official/plugin-search.html) that comes with the default vuepress theme. In particular, the Algolia [docs](https://www.algolia.com/doc/guides/getting-started/what-is-algolia/) describe that it consists of both search implementation and search analytics. So it sounds like we want to continue to use this platform if it is better than the default option. Also, do we pay for this service? [pricing page](https://www.algolia.com/pricing/)

In any case, I submitted a ticket with them yesterday to see if they can help figure out why the indexing is not working properly for some pages of the Wasabi docs.

**Comment by jesseaam** [comment]
I reached out to Algolia and they are helping me look into this issue.
```
Hi Jesse,
 
Thank you for contacting the Algolia support team. I'd be glad to assist!
 
If I'm understanding the issue correctly, it sounds like you're using a deprecated version of Docsearch. You can find all information related to Docsearch -- including full documentation and a "Getting Started" guide -- at https://docsearch.algolia.com/.
 
Because you're using a deprecated version of Docsearch, I've had to request special access to your index in order to review your records to see why "WHAT DOES THE PRIVACY PROGRESS MEAN?" might not be returning results.
 
Once I have access, my investigation might reveal whether the issue is connected to how your documents are being indexed, but regardless, we would recommend following the implementation guidelines for the latest version of Docsearch at the link I shared above.
 
Please let me know if you have any other questions.
 
Many thanks!
Steven Kaiser
Algolia Developer Support Engineer
```

**Comment by jesseaam** [comment]
Hi all, to solve this issue we need to upgrade DocSearch from version2 to version3. Can somebody help with this?

Here is what the folks at Algolia told me:

>I would highly recommend migrating to the current version (v3) rather than v2.6.3. You can read about the advantages [here](https://docsearch.algolia.com/docs/migrating-from-legacy). The most noteworthy improvements:
The DocSearch infrastructure now leverages the [Algolia Crawler](https://www.algolia.com/products/search-and-discovery/crawler/) instead of the legacy scraper.
We now provide [a web interface](https://crawler.algolia.com/) so that you no longer need to install any tooling on your side if you want to maintain or update your index.
 
>You can also refer to our [Installation Guide for DocSearch v3](https://docsearch.algolia.com/docs/DocSearch-v3#installation) and our [Guide To Migrating From DocSearch v2](https://docsearch.algolia.com/docs/migrating-from-v2) for more details.

**Comment by jesseaam** [comment]
@CAnorbo, are you familiar with VuePress? Can you make this upgrade?

**Comment by yahiheb** [comment]
@jesseaam @CAnorbo I have checked #1247 and it fixes this issue and some other issues too, so we should merge it soon.

Thank you both for your efforts.
