### ISSUE TITLE
No data after connecting to own full node

### ISSUE THREAD

**Issue by compane** [zkSNACKs/WasabiDoc#133]
I'm trying to connect wasabi to my own full node. The connection seems to be established but data is displayed as ######. Any advise?

Wasabi version: 1.1.6
OS: Manjaro 18.0.4
Full node: 0.18.0 on Ubuntu 18.04

**Comment by yahiheb** [comment]
I think the right place for this issue is Wasabi Wallet's main [repository](https://github.com/zkSNACKs/WalletWasabi). Ask your question [here](https://github.com/zkSNACKs/WalletWasabi/issues).
This repository is better suited for documentation related issues.

**Comment by MaxHillebrand** [comment]
Yes, this is the documentation repository, and the main repo is the right place for such an issue. Could you please ask over there, I'll answer asap :)

@yahiheb, this is the second time a peer opens the main issue in the repo... I will write something more precise in the #132, can you please review so that I can merge and we see if this will help explain the differences?

**Comment by yahiheb** [comment]
Yes I will take a look.

**Comment by dennisreimann** [comment]
Regarding the actual issue: Is it possible that you are using Wasabi in „Lurking wife mode“?
