### ISSUE TITLE
Use of uncommon words.

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#143]
I am not sure if the use of `wasabikas` or `peers` or similar words in the documentation is really helpful. I think we need to be very simple and clear when we are trying to explain things.

**Comment by MaxHillebrand** [comment]
Good question, I'm not sure what's better.

I like to have some fun in this doc.
I also think it's good to build some community and culture around Wasabi. 

`Wasabika` is used for a long time in the Dojo, and I think this is a great word to describe the builders of Wasabi in general. 
`Peers` are those who use Bitcoin and Wasabi, because they are literally peers in the network, or in the CoinJoin.

I think it's fitting, but am open to conversation about how to make it better.

**Comment by benthecarman** [comment]
A solution is to make a terms pages with a list of terms people might not know. This can explain things like wasabikas as well as something as simple as a node.

**Comment by MaxHillebrand** [comment]
I'm thinking about something like this in #136, maybe have a way that often used words have a highlight / pop up with a short two sentence explanation with link to more details?

**Comment by yahiheb** [comment]
`Timechain` vs `Blockchain`

**Comment by benthecarman** [comment]
`Blockchain` for sure. It is the term everyone knows, `Timechain` is originally from Satoshi's first implementation of bitcoin and is mostly just a meme under bitcoiners.
