### ISSUE TITLE
searchbar not working properly

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1624]
### broken:
cannot find a simple FAQs like _What do I need to recover my wallet_ or how to enable manual coin control

there are links that give 404

### not working as expected:

type in privacy suggestions, then it will not find the [privacy suggestions section at _Send_
](https://docs.wasabiwallet.io/using-wasabi/Send.html#privacy-suggestions)

**Comment by yahiheb** [comment]
If you type in `privacy suggestions` and you click the first result you get a broken because the `TechnicalOverview.html` was already removed.

This is because of using the old index as @CAnorbo has mentioned in a [previous comment](https://github.com/zkSNACKs/WasabiDoc/issues/1614#issuecomment-1813125785) regarding such issues.

**Comment by CAnorbo** [comment]
I sent the access to @yahiheb where you can manage the index configuration.
Deleted the "Privacy suggestions" 404 link.

**Comment by MarnixCroes** [comment]
it's broken, cannot find how to speed up a tx
if you type `speed`, it will show results like `spend` and `seed` (phrase)
