### ISSUE TITLE
Build first version of GitBook

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#2]
As mentioned in the [original issue](https://github.com/zkSNACKs/WalletWasabi/issues/1887), we will start to use [GitBook](https://www.gitbook.com/) to build the static website of this documentation repository.
@Thunder-B has already build [test version](https://wasabi-test.gitbook.io/wasabi-docs-test/) of a [repository](https://github.com/thunder-B/wasabi-docs-test).

### ToDo

@Thunder-B, can you please make a PR with the GitBook setup for this repo? :kissing_heart:

**Comment by thunder-B** [comment]
Man that's awesome! Ok so to move this forward a few things need to happen.

### GitBook Account
The first step is to have one of the maintainers of the repo (are you one yet @MaxHillebrand?) create an account on GitBook and create and "organization" (this will allow you to add people if you wish to have more than one person in control of the GitBook). Then you create a "space" (this is really just the website itself), and fiddle around within the space to find a tab called _integrations_ on the left, and link a GitHub repo using that. The person needs to be maintainer or owner of the repo to be able to do the link. You then need to choose something like "I edit my files on GitHub" as an option.

### Propose strucutre to WasabiDocs repo
I can make a small PR that will add the `.gitbook.yaml` and the `SUMMARY.md` files in a `/docs/` directory inside the repo. I think keeping a `/docs/` directory might be a good idea so that the root directory can still contain a README and CONTRIBUTING files that are specific to the WasabiDocs repo without being part of the documentation. I can explain more in the PR if needed.

**Comment by MaxHillebrand** [comment]
Very good, thanks!

I think it's best if @nopara73 creates this GitBook organization - he maybe even has already an account for Programming the --Block-- *Timechain - and then to add me as contributor to that project?

Yes, it sounds good to have a separate `/docs/` directory with all this stuff. Thanks for your PR :)

**Comment by MaxHillebrand** [comment]
#5 & #9 restructure to have a `/docs/` for GitBook convenience - #11 fixes links to this structure.

**Comment by MaxHillebrand** [comment]
### Update

Nopara has created the GitBook account [@zksnacks-wasabidoc](https://app.gitbook.com/@zksnacks-wasabidoc) and the [WasabiDocumentation](https://app.gitbook.com/@zksnacks-wasabidoc/wasabi-documentation] work space.

I have maintainer access to this GitBook account. 

However, I cannot myself link to the `/ZkSnacks/WasabiDoc/` repository, so Nopara has to do this one more step.

I have already requested the free premium model because Wasabi is libre & open source software - though they have some clause in there that the project should be non-profit. I'm not sure what they will say in regards to the opt-in advanced coin join feature, because the wallet is great even with out this. So let's see...

**Comment by MaxHillebrand** [comment]
And we have a first version of the master-branch GitBook available [here](https://zksnacks.gitbook.io/wasabidoc/)!! 

Now we can compare it to the VuePress setup #26 which is live [here](https://wasabi.incodewetrust.com/).

**Comment by MaxHillebrand** [comment]
We decided to use VuePress - merged by #26, thus closing this issue.
