### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WasabiDoc#465]
I got this Reddit message.

> page location https://docs.wasabiwallet.io/using-wasabi/InstallPackage.html

> The "manual import" instructions should (imo) be moved to just below the Debian/ubuntu instructions, as the manual import instructions are for some flavor of linux.

> Even better. imo. since there are instructions for multiple flavors of linux, perhaps "if you get errors try a manual import" would be best as a separate page and just linked to below each linux distros instructions.

**Comment by yahiheb** [comment]
I think the user simply didn't download zkSNACKs' PGP public key correctly and that is why he had issues to verify Wasabi.
Maybe we should link to the raw file instead of the github page.

Also the "manual import" instructions are for windows, for other OS they simply should follow the four first steps in that manual.

**Comment by nopara73** [comment]
> Maybe we should link to the raw file instead of the github page.

We had this conversation before. The reasoning is, easily accessible github history provides an extra layer of security.
