### ISSUE TITLE
Weird magnifier icon in the search box

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#491]
![Capture](https://user-images.githubusercontent.com/52379387/72574141-517d4400-38c8-11ea-9ab7-ffffb271c409.PNG)

It used to be only one magnifier.

**Comment by yahiheb** [comment]
Now it is back to be normal.
![Capture](https://user-images.githubusercontent.com/52379387/72578360-2ac60a00-38d6-11ea-9abd-3079047efd8c.PNG)

**Comment by MaxHillebrand** [comment]
I've never seen this before...
Can you write how to reproduce?

**Comment by yahiheb** [comment]
I don't know how to reproduce.

**Comment by yahiheb** [comment]
I can see that again, but I don't know how to reproduce it.

**Comment by RiccardoMasutti** [comment]
Happens only in mobile view ( > 900 px). I'm investigating

**Comment by RiccardoMasutti** [comment]
`<input id="algolia-search-input" class="search-query ds-input" placeholder="Search the docs..." autocomplete="off" spellcheck="false" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-label="search input" aria-owns="algolia-autocomplete-listbox-0" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;">`

This causes the double search icon.
It probably happens since https://github.com/zkSNACKs/WasabiDoc/commit/c8b7589012b2c722c42087897832ba19de67c28d#diff-2925b87683d10b17b2ee85de7cc6ca84 or https://github.com/zkSNACKs/WasabiDoc/commit/a5363ff21d5c341b0225ded319971395c8a728b0#diff-d669c10d59b56bb12a815dd48ce8d884 or https://github.com/zkSNACKs/WasabiDoc/commit/bac7baafc86dd5dad02ee84b8e746212eef26f2d#diff-d669c10d59b56bb12a815dd48ce8d884

**Comment by yahiheb** [comment]
Maybe it is just a problem on my end, but I see this again.
![Capture](https://user-images.githubusercontent.com/52379387/73136156-dac01380-404a-11ea-8c9a-e4743ccf2783.PNG)

**Comment by MaxHillebrand** [comment]
Yes. FYI, this is also after clearing the browser cache.

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand @yahiheb Can't reproduce. Everything works for me

**Comment by dennisreimann** [comment]
Might be browser specific, I'll take a closer look! 🕵️‍♂️

**Comment by MaxHillebrand** [comment]
FYI, I'm using firefox in Fedora 30 VM of Qubes 4, add-ons are: privacy batcher, HTTPS Everyhwere, UBlock Origin and Dark Reader.

**Comment by dennisreimann** [comment]
Please try it with #527.

**Comment by yahiheb** [comment]
The problem is I don't know how that happens.
It happened to me only 3 times.

**Comment by dennisreimann** [comment]
It seems to be a really weird edge case where maybe switching the breakpoints/changing browser width is involved. 
I could not reproduce it, but saw that there are two search inputs – one overlays the other. Now I have hidden one of them, hope this does not lead to the next strange error.
