### ISSUE TITLE
[Bug] Clicking "CoinJoin" link in the FAQ brings you a 404 error

### ISSUE THREAD

**Issue by benthecarman** [zkSNACKs/WasabiDoc#63]
It attempts to take you to: https://docs.wasabiwallet.io/FAQ-UseWasabi.html#coinjoin it should be: https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#coinjoin

**Comment by MaxHillebrand** [comment]
Yes, good catch!
This is in the `README.md` of the `/FAQ/` repo, and I'm not even sure what we should put in here... Currently it is an old table of content, that is probably already out of date and a bunch of broken links... We are now using the vuepress automatic `[[toc]]` function, which solves exactly this problem - but this only works for headers in the same markdown - not in different ones like this readme has it now.

So I guess the proper solution is to re-write the `README.md` in all three pillars + FAQ so that it is an introduction to this structure with working links for the content.

**Comment by MaxHillebrand** [comment]
Also, the table of content is in the sidebar menu, so I doubt that we even need this separate file with all the links, it's just duplicate and not even automatic, so a huge pita to maintain.

**Comment by MaxHillebrand** [comment]
https://github.com/zkSNACKs/WasabiDoc/commit/ed10c862caa1afacec3492fa9e86ad037a0ffbd5 removes this manual table of content, it is broken and useless.

We need to re-write the four README's in the docs in one of the next steps so that they have good introduction to that pillar.
