### ISSUE TITLE
Redirect links doesn't work

### ISSUE THREAD

**Issue by PeterXMR** [zkSNACKs/WasabiDoc#877]
I'm getting **404** while opening redirect links on this page ->
https://github.com/zkSNACKs/WasabiDoc/tree/master/docs/building-wasabi/
 I guess Its becouse of not updated filePath,
I'll check that and fix it in a minute.

**Comment by yahiheb** [comment]
They work in the docs website
https://docs.wasabiwallet.io/building-wasabi/

**Comment by xanoni** [comment]
@yahiheb I gotta admit that I was also confused by this. The way this repo is presented (see below), it intuitively suggests one should be able to browse the documentation from Github. However, most of the relative links are broken because they are missing the "/docs/" in the path. I can confirm that it works after building the docs with npm.

https://github.com/zkSNACKs/WasabiDoc/

![image](https://user-images.githubusercontent.com/77220130/120120918-b7d9ce00-c16e-11eb-8189-e55e48d6a348.png)
